# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.berkshelf.enabled = true
  config.vm.box = "precise64"
  config.vm.network :forwarded_port, guest: 3306, host: 33306
  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "apt"
    chef.add_recipe "mysql::server"
    chef.json = {
      "mysql" => {
        "allow_remote_root" => true,
        "bind_address" => "0.0.0.0",
        "server_root_password" => ENV["MYSQL_ROOT_PASSWORD"],
        "server_repl_password" => ENV["MYSQL_REPL_PASSWORD"],
        "server_debian_password" => ENV["MYSQL_DEBIAN_PASSWORD"]
      }
    }
   end
end
